name: Update README

on:
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Run Python script to update README
      env:
        USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scripts/readme_stats.py 

    - name: Commit and push if README changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # git tag -a -m "<msg>" <tag> <commit hash>
        git diff --exit-code -- README.md || git commit -am "Update README with GitHub stats" && git push
